Ramp up
cloud-bulldozer/ocm-api-load pull request #49
Opened 2021-10-29 18:04 UTC by chentex

### Description

Adding ramp up functionality to the suite.

### Fixes

2021-12-07 15:41 UTC, troy0820 requested changes
@chentex Overall this looks really good.  A lot of good work in this PR 👍🏽.  Just a couple of changes requested and we should be good to go.

2021-12-07 15:41 UTC, troy0820 commented on pkg/tests/run.go
> +	ctx             context.Context
```suggestion
```
As discussed in previous comment.

2021-12-07 16:09 UTC, dry923 commented
@chentex Not sure if this functionality is in there (still walking through the code) but can it/it might be useful if it could have a ramp up time and a test time. So it can ramp up for 30 minutes but the entire test will run for 60.

2021-12-07 16:32 UTC, chentex commented
So @dry923 if I get you right you wan t something like this:

- Endpoint A:
  - duration: 60 min
  - ramp duration: 30 min
  
And this will run a normal test with a normal `rate` or the `start-rate` for 30 min and then ramp up for 30 min, that it's the remaining of the duration.

2021-12-08 16:07 UTC, chentex commented on pkg/ramping/exponential.go
> +	delta       float64
For the math operations we needed floats, I will change them to int to better reflect the values, and do the conversions in other palce

2021-12-10 14:37 UTC, dry923 commented on cmd/ocm-load-test.go
> +	// If multiple AWS account are needed use use the config file
Nit but you have "use use" and you probably just want 1.

2021-12-10 14:58 UTC, dry923 approved these changes
LGTM! Great work!

2021-12-10 15:24 UTC, troy0820 commented
LGTM but can we squash these commits?  NICE Work @chentex !!!! 🎉

2022-01-10 14:49 UTC, troy0820 approved these changes
LGTM 👍🏽

2022-01-10 15:05 UTC, merged